name: Build website with Hugo

on: [ workflow_dispatch, workflow_call ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Setup Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0'
      - name: "Build website"
        run: "hugo --minify"
